version: '3.9'

services:

  db:
    image: 
    container_name: "Balanceo_carga"
    env_file: 
      - database.env
    ports: 
      - 
    volumes: 
      - 

  server:
    build: 
      context: .
      dockerfile: DockerFile
    depends_on:
      - db
    ports:
      - "5000:5000"

  volumes: 
    db-data: